---
title: "Day of the Race"
output: html_notebook
---

```{r}
# create friends vector:
friends <- c("Megan", "Janet", "Tina")
```

```{r}
# race info list:
info_list <- list(
  Esther = list(
    jersey = 3432,
    color = "purple"
  ),
  Feng = list(
    jersey = 4221,
    color = "blue"
  ),
  Megan = list(
    jersey = 1363,
    color = "green"
  ),
  Janet = list(
    jersey = 6729,
    color = "green"
  ),
  Tina = list(
    jersey = 7501,
    color = "orange"
  )
)
```

```{r}
print_information <- function(name) {
  print(paste(name, "is #", info_list[[name]]$jersey, "wearing the color", info_list[[name]]$color))
}
# call the print_information function on the friends vector:
# print_information("Megan")
# print_information("Janet")
# print_information("Tina")
for (f in friends) {
  print_information(f)
}
```

```{r}
race_results <- c("Gi", "Francesca", "Lea", "Vivian", "Jessica", "Esther", "Mary", "Yasmina", "Megan", "Janet", "Tiffany", "Kishan", "Feng", "Z", "Tina")
```

```{r}
# write find_place():
find_place <- function(runner) {
   for (place in 1:length(race_results)) {
      if (race_results[place] == runner) {
        return(place)
      }
   }
   return(length(race_results) + 1)
}
```

```{r}
# call and apply find_place():
find_place("Francesca")
lapply(friends, find_place)
sapply(friends, find_place)
```